name: publish_redcode

on:
  release:
    types:
      - published

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Release
      id: release
      uses: bruceadams/get-release@v1.2.2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install --locked

    - name: Package extension
      run: npm run package -- --out ${{ steps.release.outputs.tag_name }}.vsix

    - name: Upload extension to Github
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ${{ steps.release.outputs.tag_name }}.vsix
        asset_name: ${{ steps.release.outputs.tag_name }}.vsix
        asset_content_type: application/vsix

    - name: Publish extension to VSCode marketplace
      run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
